version: '2'

services:
  node: 
    image: node:7.7
    volumes:
      - ./:/code/
    working_dir: /code/
    env_file: .env
    ports:
      - "8888:8888"
    depends_on:
      - mongo

  mongo:
    image: mongo:3.0
    env_file: .env
    volumes:
      - ./build/:/build/
    entrypoint: /usr/bin/mongod
