version: '2'

services:
    node: 
        image: node:7.7
        volumes:
            - ./:/code/
        working_dir: /code/
        ports:
            - "8888:8888"
        depends_on:
            - mongo

    mongo:
        image: mongo:3.0
